apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: register-component-template
  title: Register component template
  description: Registers a Catalog component
spec:
  owner: development
  type: service
  parameters:
    - title: Fill in some steps
      required:
        - component_id
      properties:
        component_id:
          title: Component name
          type: string
          description: Provide a component (microservice) name
          pattern: '^([a-zA-Z][a-zA-Z0-9]*)(-[a-zA-Z0-9]+)*$'
  steps:
    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: https://github.com/rcorozo/${{ parameters.component_id }}/blob/main
        catalogInfoPath: "/catalog-info.yaml"
  output:
    links:
      - title: Repository
        url: https://github.com/rcorozo//${{ parameters.component_id }}


